version: '3.8'

services:
  paddleocr-api:
    build: .
    container_name: paddleocr-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_URL=redis://redis:6379
      - API_KEY=${PADDLEOCR_API_KEY:-paddleocr-key-2024}
      - ENABLE_GPU=${ENABLE_GPU:-false}
      - PADDLE_OCR_LANG=${PADDLE_OCR_LANG:-pt}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - WORKERS=${WORKERS:-2}
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: paddleocr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: paddleocr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - paddleocr-api
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: paddleocr-network
