[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 600 --max-requests 1000 --max-requests-jitter 100 --preload --log-level info --access-logfile - --error-logfile - api_server:app"
