[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
region = "us-west1"

[build.buildpacks]
enabled = false

[deploy.runtime]
minInstances = 1
maxInstances = 1
memoryLimit = "2048"
startupProbeInitialDelaySeconds = 60
startupProbeTimeoutSeconds = 10
startupProbePeriodSeconds = 10
startupProbeFailureThreshold = 30