[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 300 api_server:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
