[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:5000 api_server:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
